deployment:
  tasks:
    - export DEPLOYPATH=/home/tuguttrg/public_html
    - /bin/cp /home/tuguttrg/repositories/tuguiamedicani/index.html $DEPLOYPATH/
    - /bin/cp -R /home/tuguttrg/repositories/tuguiamedicani/assets $DEPLOYPATH/
    - /bin/sed -i 's#<li><a href="/assets/views/Acercade.html">Acerca de Nosotros</a></li>#<li><a href="Acercade.html">Acerca de Nosotros</a></li>#g' $DEPLOYPATH/assets/views/header.html
    - /bin/sed -i 's#<li><a href="/assets/views/velez.html">Fernando Vélez Paiz</a></li>#<li><a href="velez.html">Fernando Vélez Paiz</a></li>#g' $DEPLOYPATH/assets/views/header.html